name: Audio Transcription with Gemini 2.5 Pro

on:
  workflow_dispatch:  # Только ручной запуск
    inputs:
      use_reference_audio:
        description: 'Использовать образец голоса Алексея'
        required: false
        default: 'true'
        type: choice
        options:
        - 'true'
        - 'false'
      api_delay:
        description: 'Задержка между запросами (секунды)'
        required: false
        default: '3.0'
        type: string

jobs:
  transcribe:
    runs-on: ubuntu-latest
    timeout-minutes: 480  # 8 часов максимум
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        lfs: true  # Включаем поддержку LFS
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run transcription
      env:
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        SOURCE_DIR: 'audio_files'
        OUTPUT_DIR: 'transcriptions'
        API_DELAY: ${{ github.event.inputs.api_delay || '3.0' }}
        USE_REFERENCE_AUDIO: ${{ github.event.inputs.use_reference_audio || 'true' }}
      run: |
        python transcribe.py
    
    - name: Commit and push results
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add transcriptions/ audio_files/
        git diff --staged --quiet || git commit -m "Add transcriptions (Gemini 2.5 Pro) and rename processed files"
        git push
